version: '3.9'
 
networks:
  haranet:
 
volumes:
  db_data: {}
 
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - haranet
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - haranet
    depends_on:
      - db
  
  website:
    image: wordpress:latest
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/conf.d/wp-php.ini
      - ./site1:/var/www/html/site1
      - ./site2:/var/www/html/site2
      - ./site3:/var/www/html/site3
      - ./conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - /etc/hosts:/etc/hosts
    environment:
      - VIRTUAL_HOSTS=site1,site2,site3
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
    networks:
      - haranet
    depends_on:
      - db